name: Store GPG Keys in AWS Secrets Manager

on:
  workflow_dispatch:

jobs:
  store-gpg-keys:
    runs-on: ubuntu-latest

    steps:
      - name: Install AWS CLI
        run: sudo apt-get install -y awscli

      - name: Check if GPG Keys exist in AWS Secrets Manager
        id: check_secret
        run: |
          set +e
          aws secretsmanager describe-secret --secret-id landslide-monitoring-usb-driver-gpg-keys --region ${{ secrets.AWS_REGION }}
          if [ $? -eq 0 ]; then
            echo "secret_exists=true" >> $GITHUB_ENV
          else
            echo "secret_exists=false" >> $GITHUB_ENV
          fi
          set -e
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Create GPG Keys in AWS Secrets Manager (if not exists)
        if: env.secret_exists == 'false'
        run: |
          aws secretsmanager create-secret \
            --name landslide-monitoring-usb-driver-gpg-keys \
            --secret-string "{\"GPG_PUBLIC_KEY\": \"${{ secrets.GPG_PUBLIC_KEY }}\", \"GPG_PRIVATE_KEY\": \"${{ secrets.GPG_PRIVATE_KEY }}\"}" \
            --region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Update GPG Keys in AWS Secrets Manager (if exists)
        if: env.secret_exists == 'true'
        run: |
          aws secretsmanager update-secret \
            --secret-id landslide-monitoring-usb-driver-gpg-keys \
            --secret-string "{\"GPG_PUBLIC_KEY\": \"${{ secrets.GPG_PUBLIC_KEY }}\", \"GPG_PRIVATE_KEY\": \"${{ secrets.GPG_PRIVATE_KEY }}\"}" \
            --region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
